export interface Laptop {
  name: string;
  price: number;
  os: "MacOS" | "Windows" | "ChromeOS";
  useCase: string[];
  screenSize: number;
  storage: number;
  gpu?: string;
  description: string;
}

export const laptops: Laptop[] = [
  {
    name: "MacBook Air M3 13-inch",
    price: 1099,
    os: "MacOS",
    useCase: ["General", "Work"],
    screenSize: 13,
    storage: 256,
    description: "Lightweight and efficient, perfect for everyday tasks and students."
  },
  {
    name: "MacBook Air M3 15-inch",
    price: 1299,
    os: "MacOS",
    useCase: ["General", "Work", "Media"],
    screenSize: 15,
    storage: 512,
    description: "Larger screen for multitasking and media consumption.",
  },
  {
    name: "MacBook Pro 14-inch M3 Pro",
    price: 1999,
    os: "MacOS",
    useCase: ["Development", "Media", "Work"],
    screenSize: 14,
    storage: 512,
    gpu: "M3 Pro (18-core GPU)",
    description: "Powerful performance for video editing, development, and creative work.",
  },
  {
    name: "MacBook Pro 16-inch M3 Max",
    price: 3499,
    os: "MacOS",
    useCase: ["Media", "Development"],
    screenSize: 16,
    storage: 1024,
    gpu: "M3 Max (40-core GPU)",
    description: "Top-tier performance for professional video editing and 3D work.",
  },
  {
    name: "Dell XPS 13",
    price: 999,
    os: "Windows",
    useCase: ["General", "Work"],
    screenSize: 13,
    storage: 512,
    description: "Compact Windows laptop with premium build quality.",
  },
  {
    name: "Lenovo ThinkPad X1 Carbon",
    price: 1399,
    os: "Windows",
    useCase: ["Work", "Development"],
    screenSize: 14,
    storage: 512,
    description: "Business-class laptop with excellent keyboard and durability.",
  },
  {
    name: "ASUS ROG Zephyrus G14",
    price: 1599,
    os: "Windows",
    useCase: ["Gaming", "Media"],
    screenSize: 14,
    storage: 1024,
    gpu: "NVIDIA RTX 4060",
    description: "Compact gaming laptop with excellent performance and battery life.",
  },
  {
    name: "MSI Raider GE78",
    price: 2499,
    os: "Windows",
    useCase: ["Gaming", "Media"],
    screenSize: 17,
    storage: 2048,
    gpu: "NVIDIA RTX 4070",
    description: "High-end gaming laptop with large screen and powerful specs.",
  },
  {
    name: "Lenovo Chromebook Plus",
    price: 749,
    os: "ChromeOS",
    useCase: ["General", "Work"],
    screenSize: 14,
    storage: 256,
    description: "Affordable and simple laptop for basic tasks and web browsing.",
  },
  {
    name: "Microsoft Surface Laptop 5",
    price: 1299,
    os: "Windows",
    useCase: ["Work", "General"],
    screenSize: 13,
    storage: 512,
    description: "Sleek Windows laptop with touchscreen and premium design.",
  },
  {
    name: "Lenovo IdeaPad Gaming 3",
    price: 799,
    os: "Windows",
    useCase: ["Gaming", "General"],
    screenSize: 15,
    storage: 512,
    gpu: "NVIDIA RTX 4050",
    description: "Budget-friendly gaming laptop with solid 1080p performance.",
  },
  {
    name: "Acer Chromebook Spin 714",
    price: 729,
    os: "ChromeOS",
    useCase: ["General", "Work"],
    screenSize: 14,
    storage: 256,
    description: "Premium Chromebook with 2-in-1 design and long battery life.",
  },
  {
    name: "ASUS Vivobook 15",
    price: 549,
    os: "Windows",
    useCase: ["General", "Work"],
    screenSize: 15,
    storage: 256,
    description: "Affordable everyday laptop for basic productivity and web browsing.",
  },
  {
    name: "HP Pavilion Plus 14",
    price: 899,
    os: "Windows",
    useCase: ["Development", "Media", "Work"],
    screenSize: 14,
    storage: 512,
    description: "Mid-range laptop with OLED display, great for content creation.",
  },
  {
    name: "Lenovo Legion 5 Pro",
    price: 1399,
    os: "Windows",
    useCase: ["Gaming", "Media", "Development"],
    screenSize: 16,
    storage: 1024,
    gpu: "NVIDIA RTX 4060",
    description: "Excellent gaming laptop with high refresh rate display.",
  },
  {
    name: "Razer Blade 14",
    price: 2199,
    os: "Windows",
    useCase: ["Gaming", "Media", "Development"],
    screenSize: 14,
    storage: 1024,
    gpu: "NVIDIA RTX 4070",
    description: "Compact premium gaming laptop with excellent build quality.",
  },
  {
    name: "Framework Laptop 13",
    price: 1049,
    os: "Windows",
    useCase: ["Development", "Work", "General"],
    screenSize: 13,
    storage: 512,
    description: "Modular and repairable laptop perfect for developers and tinkerers.",
  },
  {
    name: "LG Gram 17",
    price: 1699,
    os: "Windows",
    useCase: ["Work", "Media", "Development"],
    screenSize: 17,
    storage: 1024,
    description: "Ultra-lightweight 17-inch laptop with excellent battery life.",
  },
  {
    name: "Google Pixelbook Go",
    price: 649,
    os: "ChromeOS",
    useCase: ["General", "Work"],
    screenSize: 13,
    storage: 128,
    description: "Lightweight ChromeOS laptop with premium design and portability.",
  },
  {
    name: "Dell Inspiron 15 3000",
    price: 479,
    os: "Windows",
    useCase: ["General", "Work"],
    screenSize: 15,
    storage: 256,
    description: "Budget-friendly Windows laptop for basic everyday tasks.",
  },
  {
    name: "Acer Aspire 5",
    price: 599,
    os: "Windows",
    useCase: ["General", "Work"],
    screenSize: 15,
    storage: 512,
    description: "Reliable budget laptop with good value for everyday computing.",
  },
  {
    name: "ASUS TUF Gaming A15",
    price: 899,
    os: "Windows",
    useCase: ["Gaming", "General"],
    screenSize: 15,
    storage: 512,
    gpu: "NVIDIA RTX 4060",
    description: "Durable gaming laptop with good thermal performance.",
  },
  {
    name: "HP Envy x360 15",
    price: 949,
    os: "Windows",
    useCase: ["Media", "Work", "General"],
    screenSize: 15,
    storage: 512,
    description: "2-in-1 convertible laptop ideal for creative work and media consumption.",
  },
  {
    name: "Alienware m18",
    price: 2899,
    os: "Windows",
    useCase: ["Gaming", "Media"],
    screenSize: 18,
    storage: 2048,
    gpu: "NVIDIA RTX 4070",
    description: "Massive gaming powerhouse with desktop-class performance.",
  },
  {
    name: "Acer Chromebook 314",
    price: 349,
    os: "ChromeOS",
    useCase: ["General"],
    screenSize: 14,
    storage: 64,
    description: "Ultra-affordable Chromebook for basic web browsing and schoolwork.",
  },
  {
    name: "Microsoft Surface Laptop Studio 2",
    price: 2099,
    os: "Windows",
    useCase: ["Development", "Media", "Work"],
    screenSize: 14,
    storage: 512,
    gpu: "NVIDIA RTX 4050",
    description: "Versatile 2-in-1 laptop with powerful specs for creative professionals.",
  },
  {
    name: "Samsung Galaxy Chromebook 2",
    price: 549,
    os: "ChromeOS",
    useCase: ["General", "Work", "Media"],
    screenSize: 13,
    storage: 128,
    description: "Stylish Chromebook with vibrant QLED display.",
  },
  {
    name: "Dell G15 Gaming Laptop",
    price: 749,
    os: "Windows",
    useCase: ["Gaming", "General"],
    screenSize: 15,
    storage: 512,
    gpu: "NVIDIA GTX 1650",
    description: "Entry-level gaming laptop with solid build and thermals.",
  },
  {
    name: "ASUS ProArt Studiobook 16",
    price: 2399,
    os: "Windows",
    useCase: ["Media", "Development"],
    screenSize: 16,
    storage: 1024,
    gpu: "NVIDIA RTX 4060",
    description: "Professional-grade laptop for video editing and 3D rendering.",
  },
  {
    name: "Lenovo Yoga 9i",
    price: 1399,
    os: "Windows",
    useCase: ["Work", "Media", "General"],
    screenSize: 14,
    storage: 512,
    description: "Premium 2-in-1 laptop with excellent audio and display quality.",
  }
];
